Feature/map interactive
WildCodeSchool/chasseurs-de-vignes pull request #1
Opened 2019-10-24 08:28 UTC by Mozzaco

La map est cliquable et renvoi la region en console.log. 
Les filtres seront ajouté plus tard.

2019-10-24 15:32 UTC, FPaurisse commented
OK for the moment...

2019-10-24 15:47 UTC, FPaurisse approved these changes

2019-10-26 08:56 UTC, Aebrathia requested changes
You have warnings in your console. Be careful not to push code with warnings or errors.

Your commit "region cliquable" is not clear enough and does not respect our conventions. It would have been better to write "Make regions clickable".

2019-10-26 08:56 UTC, Aebrathia commented on src/components/Map.js
> +  }
Your component is only presentational, it does not have state nor any logic. Use a function instead.

2019-10-26 08:56 UTC, Aebrathia commented on src/components/Map.js
> +export default Map;
Add missing newline

2019-10-31 12:16 UTC, Aebrathia approved these changes

2019-10-31 12:17 UTC, Aebrathia commented
Congrats 2nd PR merged !

2019-10-31 12:17 UTC, merged