Feature/geoloc button
WildCodeSchool/chasseurs-de-vignes pull request #2
Opened 2019-10-24 14:36 UTC by FPaurisse

2019-10-24 15:34 UTC, TanguyDuponchelle approved these changes

2019-10-25 12:05 UTC, Aebrathia requested changes

2019-10-25 12:05 UTC, Aebrathia commented on src/App.js
> +  }
Your component does not have a state, therefore prefer using a function instead.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +class displayAoc extends React.Component {
- Components should be writte, in PascalCase.
- Use `extends Component`
- Components are not actions, use a descriptive UI term like AocsList or equivalent

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +    }%2C${this.props.longitude}%2C${50000}`;
You can destructure `this.props` along with your state :

```
const { latitude, longitude } = this.props;
```

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +    let url = `https://plateforme.api-agro.fr/api/records/1.0/search/?dataset=delimitation-parcellaire-des-aoc-viticoles&start=${countStart}&rows=${10}&facet=appellatio&facet=denominati&facet=crinao&
Use `const`

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +  }
Duplicate code with `componentDidMount`. Either use `this.getData()` in `componentDidMount` or remove `getData`.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +    let myLongitude = this.props.longitude;
Destructure your objects and use const :

```
const { latitude, longitude } = this.props;
```

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +    createObjAoc = this.state.infos.map(function(aoc) {
You can directly write :

```
const aocsList = this.state.infos.map(aoc => /* … */);
```

- You don't need to initiate a variable beforehand.
- You should use an arrow function.
- You should use a name that describe what is inside the variable and not a verb.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +      }
Be careful this will sometime return undefined values in the new array, like this `[ {}, undefined, {}, {}, undefined]`.

This will be a problem because you wrote :

```
<li key={aoc.id_app}>
    AOC {aoc.name_app} ({aoc.name_com_app}) › {aoc.distance} km
</li>
```

And it will try to access properties like id_app but aoc will be undefined and it will crash your application.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +        <p>{this.state.total} résultats</p>
You can and should destructure at the beginning of your render

2019-10-25 12:05 UTC, Aebrathia commented on src/components/DisplayAoc.js
> +    })
You should compute the data before you put them in the state. Otherwise, they will be recomputed each time the component renders and it will cause performance issues due to how React handle rerenders.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/GeoButton.js
> +class GeoButton extends React.Component {
Use `extends Component`

2019-10-25 12:05 UTC, Aebrathia commented on src/components/GeoButton.js
> +    this.getPosition = this.getPosition.bind(this);
Instead of this line you can replace line 15 with :

`getPosition = () => {`

Since it's an arrow function, `this` binding will be correct.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/GeoButton.js
> +            longitude={this.state.longitude}
Destructure `this.state` before the return, your code will be easier to read.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/GeoButton.js
> +        )}
Instead of a ternary operator, you can use `latitude && longitude && (<DisplayAoc />);`

Why ? Because you don't need the "else" value

2019-10-25 12:05 UTC, Aebrathia commented on src/components/Navbar.js
> +  render() {
Don't use a class component unless you have a state.

2019-10-25 12:05 UTC, Aebrathia commented on src/components/Navbar.js
> +      </div>
Never, never, never ever use DOM manipulation inside React. You are entering the gates of Hell.

2019-10-31 12:21 UTC, Aebrathia commented
When you have time, come and we will merge this PR together. I have some questions.

2019-11-04 12:03 UTC, closed without merging