[WIP] Feature/search bar results
WildCodeSchool/chasseurs-de-vignes pull request #3
Opened 2019-10-24 14:52 UTC by TanguyDuponchelle

Hello,
SearchBar Autosuggestion has been made. Still have issue on Submit (JSX answer).

2019-10-24 15:58 UTC, FPaurisse approved these changes

2019-10-26 13:54 UTC, Aebrathia requested changes

2019-10-26 13:54 UTC, Aebrathia commented on package.json
> +    "autocomplete": "0.0.1",
Remove dead dependency. Also, this dependency is not a good choice : it is very little used and has not received any updates in 8 years.

2019-10-26 13:54 UTC, Aebrathia commented on src/App.js
> +    }
Dead code. You don't need a state. Here App is only presentational, always prefer functional components when possible.

2019-10-26 13:54 UTC, Aebrathia commented on src/components/Resultat.js
> +    render(){
Prefer functions when you don't need a state. It is simpler to write, to read and has better performances.

2019-10-26 13:54 UTC, Aebrathia commented on src/components/SearchBar.js
> +import './css/SearchBar.css'
You should put SearchBar.css and SearchBar.js together in a SearchBar folder, like this :
- `/src/components/SearchBar/SearchBar.js`
- `/src/components/SearchBar/SearchBar.css`

2019-10-26 13:54 UTC, Aebrathia commented on src/components/SearchBar.js
> +  }
Fix indentation

2019-10-26 13:54 UTC, Aebrathia commented on src/components/SearchBar.js
> +class SearchBar extends React.Component {
Use `extends Component`

2019-10-26 13:54 UTC, Aebrathia commented on src/components/SearchBar.js
> +export default SearchBar
Add missing newline

2019-10-26 13:54 UTC, Aebrathia commented on src/components/css/SearchBar.css
> +}
Remove dead code and add missing newline

2019-10-26 13:54 UTC, Aebrathia commented on src/components/css/SearchBar.css
> +}
Fix indentation and spacings.

Weird naming convention, what do you use ? BEM ?

2019-10-26 13:54 UTC, Aebrathia commented on package.json
> +    "autocomplete": "0.0.1",
Also, `react-autosuggest` is missing from dependencies. You probably used `npm install react-autosuggest --no-save`.

2019-10-26 13:54 UTC, Aebrathia commented on src/components/Resultat.js
> +class Resultat extends React.Component{
Code in english, not in French

2019-10-26 13:54 UTC, Aebrathia commented on src/components/Resultat.js
> +class Resultat extends React.Component{
Use `extends Component`.

2019-10-26 13:54 UTC, Aebrathia commented on src/components/Resultat.js
> +export default Resultat
Rename in english and add missing newline

2019-10-26 13:54 UTC, Aebrathia commented on src/components/SearchBar.js
> +          />
All your difficulties and bugs come from this package which is a bit awkward.

I suggest that you drop it and write the autocompletion yourself and/or that you spend time with me in order to explain you this component.

2020-01-21 10:06 UTC, closed without merging